apiVersion: paddlepaddle.org/v1
kind: TrainingJob
metadata:
  name: example
spec:
  image: "paddlepaddle/edl-example"
  port: 7164
  ports_num: 1
  ports_num_for_sparse: 1
  fault_tolerant: true
  trainer:
    entrypoint: "python /workspace/train_ft.py"
    workspace: "/workspace"
    passes: 50
    min-instance: 2
    max-instance: 10
    resources:
      limits:
        #alpha.kubernetes.io/nvidia-gpu: 1
        cpu: "200m"
        memory: "200Mi"
      requests:
        cpu: "200m"
        memory: "200Mi"
  pserver:
    min-instance: 2
    max-instance: 2
    resources:
      limits:
        cpu: "800m"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "600Mi"
  master:
    resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "500m"
          memory: "600Mi"