apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: student
  labels:
    edl-distill-demo-app: student
spec:
  replicas: 1
  template:
    metadata:
      name: student
      labels:
        app: student
    spec:
      hostNetwork: true
      containers:
      - name: student
        image: hub.baidubce.com/paddle-edl/paddle_edl:latest-cuda10.0-cudnn7
        imagePullPolicy: Always
        workingDir: /
        command: ['/bin/bash', '-c']
        args: ['sleep 3000']
        resources:
          requests:
            memory: 20Gi
            cpu: 2
          limits:
            memory: 20Gi
            cpu: 2
      restartPolicy: Never
